defaults:
  - model: hifigan
  - metrics: hifigan_metrics
  - datasets: ljspeech
  - dataloader: hifigan_dataloader
  - transforms: hifigan_transforms
  - _self_

inferencer:
  device_tensors: ["mel", "audio"]
  device: cuda
  save_path: "hifigan_inference"
  seed: 1
  from_pretrained: "saved_hifigan/HiFiGAN-Full data/model_best.pth"
  sample_rate: 22050
  max_duration: 4.0
